#TOPICS

INIT_NODE_NAME = "splus_bot"
CMD_VEL_TOPIC_NAME = "cmd_vel"
ODOM_TOPIC_NAME = "odom"

#CONSTANTS

DEFAULT_LOOP_RATE = 100

#ENV STUFF
MISTAKE_COEF = 0.42
DEFAULT_SPEED = 0.1
MISTAKE_ROTATE_COEF = 0.835