#TOPICS

INIT_NODE_NAME = "splus_bot"
CMD_VEL_TOPIC_NAME = "cmd_vel"
ODOM_TOPIC_NAME = "odom"
HORIZONTAL_SERVO_TOPIC_NAME = "horizontal_servo"
VERTICAL_SERVO_TOPIC_NAME = "vertical_servo"
LED_TOPIC_NAME = "led_controller"
DROP_TOPIC_NAME = "drop_flag"

#CONSTANTS

DEFAULT_LOOP_RATE = 100

#ENV STUFF
MISTAKE_COEF = 1
DEFAULT_SPEED = 0.4
DEFAULT_ANGULAR_SPEED = 0.4
MISTAKE_ROTATE_COEF = 0.835
SERIAL_PORT = "/dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0"

#COMMANDS
STOP_COMMAND_NAME = "00"
PAUSE_COMMAND_NAME = "01"
M2P_SET_X = "c1"
M2P_SET_Y = "c2"
M2P_SEND = "c3"